export const START_FETCHING_ITEMS = 'redux/items/START_FETCHING_ITEMS';
export const SUCCESS_FETCHING_ITEMS = 'redux/items/SUCCESS_FETCHING_ITEMS';
export const ERROR_FETCHING_ITEMS = 'redux/items/ERROR_FETCHING_ITEMS';
